# Generated by Django 3.1 on 2020-09-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200915_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='booking.speaker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_hour',
            field=models.CharField(blank=True, choices=[('0 ', '0 '), ('1 ', '1 '), ('2 ', '2 '), ('3 ', '3 '), ('4 ', '4 '), ('5 ', '5 '), ('6 ', '6 '), ('7 ', '7 '), ('8 ', '8 '), ('9 ', '9 '), ('10 ', '10 '), ('11 ', '11 '), ('12 ', '12 '), ('13 ', '13 '), ('14 ', '14 '), ('15 ', '15 '), ('16 ', '16 '), ('17 ', '17 '), ('18 ', '18 '), ('19 ', '19 '), ('20 ', '20 '), ('21 ', '21 '), ('22 ', '22 '), ('23 ', '23 ')], max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_hour',
            field=models.CharField(blank=True, choices=[('0 ', '0 '), ('1 ', '1 '), ('2 ', '2 '), ('3 ', '3 '), ('4 ', '4 '), ('5 ', '5 '), ('6 ', '6 '), ('7 ', '7 '), ('8 ', '8 '), ('9 ', '9 '), ('10 ', '10 '), ('11 ', '11 '), ('12 ', '12 '), ('13 ', '13 '), ('14 ', '14 '), ('15 ', '15 '), ('16 ', '16 '), ('17 ', '17 '), ('18 ', '18 '), ('19 ', '19 '), ('20 ', '20 '), ('21 ', '21 '), ('22 ', '22 '), ('23 ', '23 ')], max_length=5),
        ),
    ]
