# Generated by Django 3.1 on 2020-09-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200914_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location_id',
            new_name='location',
        ),
    ]
