# Generated by Django 3.1 on 2020-09-14 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200914_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='topic',
            new_name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 5, 0, 22, 648365, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
